### PR TITLE
docker and docker-compose configuration (fixes #568)

### LINKED ISSUE #568: Angular e2e tests
__Description:__

Description of the issue you want to raise.

__Current behaviour:__

Describe expected behaviour of application.

__Expected behaviour:__

Describe expected behaviour of application.

__Steps to reproduce:__

Please describe steps which need to be reproduce.

### PR DESCRIPTION
**Pull request by magul**
**Story / Bug id:** https://github.com/CodeForPoznan/volontulo/issues/481 (see comments: https://github.com/stxnext-csr/volontulo/pull/577)
**Reference person:** @magul
**Description:**

Providing docker and docker-compose configuration for development environment.

To setup it:
- install docker and docker-compose
- execute `docker-compose up`
- point your browser to `localhost:8000`

**New imports / dependencies:**
- N/A

**Unit Tests:**
- N/A

**What tests do I need to run to validate this change:**

Procedure described above.

### CODE REVIEW

**Comment by magul** [comment]
@riv2q @tomaszwozniak @krzysztofzuraw please review.

File: docker-entrypoint.sh [hunk 1]
```diff
@@ -0,0 +1,8 @@
+#!/bin/bash
+set -e
+
+sleep 5  # waits for another container to be ready
```
Comment (MarekBleschke) [inline docker-entrypoint.sh]: A little bit more failure resistant solution on docker docs (wait-for-postgres.sh): https://docs.docker.com/compose/startup-order/.

File: Dockerfile [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+RUN apt-get install -y python3-pip \
+                       libjpeg8 \
+                       libjpeg62-dev \
+                       libfreetype6 \
+                       libfreetype6-dev \
+                       libpq-dev \
+                       wget
+
+ENV NVM_DIR /usr/local/nvm
+ENV NODE_VERSION 4.2.0
```
Comment (MarekBleschke) [inline Dockerfile]: Just out of curiosity: why to use older version of node (currently LTS is 6.9.1)?

Comment (magul) [inline Dockerfile]: Good point, I really don't remember, but it could be the version I have on my laptop at the time. I will upgrade it and will see what happened.

**Comment by magul** [comment]
@MarekBleschke the docker/vagrant solution is a result of to much time waisted at February hackathon. It last for 8 hours and few participants have problem with setting up dev environment - I could takie 2-3 hours to set up.

I would say that we have right now two supported options to setup dev environmnet (docker/vagrant) and one manually. We will update README I we will see it this is not too much.

**Comment by MarekBleschke** [comment]
@magul Yes, sounds very reasonably :). Just wondering if in the future one solution will suffice (docker or vagrant). One less thing to support :).
From my side that was just general question, not something to block vagrant or docker solution (or both of them).
I'll try to make some time today to run docker locally and see how it goes, cheers.

File: Dockerfile (hunk 2 above)
Comment (magul) [inline Dockerfile]: Ok, I've checked it and it looks that there are some problems with installing outdated npm packages.

To not block this pull request I will create another issue to upgrade all npm dependencies and move to current node LTS.

File: docker-entrypoint.sh (hunk 1 above)
Comment (magul) [inline docker-entrypoint.sh]: I believe I have resolved it, but commit is still waiting :)

File: Dockerfile (hunk 2 above)
Comment (MarekBleschke) [inline Dockerfile]: 👍

**Comment by magul** [comment]
@MarekBleschke @riv2q please review
